### ISSUE TITLE
May I post the article translated into Japanese to our blog?

### ISSUE THREAD

**Issue by wataru86** [mrkkrp/markkarpov.com#67]
I translated [Megaparsec tutorial from IH book](https://markkarpov.com/megaparsec/megaparsec.html) into Japanese.
And I'd like to post this article to [BIGMOON Haskeller's BLOG](https://haskell.e-bigmoon.com/).

Is that okay if I post the translated article?

**Comment by mrkkrp** [comment]
Sure, happy to see my stuff translated to other languages!

**Comment by wataru86** [comment]
Thanks! Posted!
https://haskell.e-bigmoon.com/posts/2019/07-14-megaparsec-tutorial.html

**Comment by mrkkrp** [comment]
I'm going to add a link to this translation to the original article.
